name: Notify Discord

on:
  push:
    branches: ["**"]
  pull_request:
    types: [opened, reopened, closed, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          MESSAGE="🔔 **${{ github.actor }}** hizo un *${{ github.event_name }}* en **${{ github.repository }}**
          → Rama: ${{ github.ref }}
          → Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          curl -H "Content-Type: application/json" \
               -d "{\"content\":\"$MESSAGE\"}" \
               "${{ secrets.DISCORD_WEBHOOK }}"
